// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khkungmvgruvpcheowit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtoa3VuZ212Z3J1dnBjaGVvd2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NjY2NTEsImV4cCI6MjA2NDI0MjY1MX0.gOt_9jEoVtVRWLopMP0kEFBEjh0c_xTf2y-IToxmF1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
