// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihqncmegdbotcsibgzdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlocW5jbWVnZGJvdGNzaWJnemR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTMyMDksImV4cCI6MjA2NDE2OTIwOX0.7pbXCKF4EiLkydFbj3huONsPC9B1RnqgYnoYVKV5mUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);